"""empty message

Revision ID: 5805f992dd5b
Revises: d2ca64c0ba9
Create Date: 2015-10-11 20:35:06.073127

"""

# revision identifiers, used by Alembic.
revision = '5805f992dd5b'
down_revision = 'd2ca64c0ba9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dude',
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
