"""empty message

Revision ID: d2ca64c0ba9
Revises: 51f5ccfba190
Create Date: 2015-10-11 06:55:56.029990

"""

# revision identifiers, used by Alembic.
revision = 'd2ca64c0ba9'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
