"""empty message

Revision ID: 3dfd0f061d9f
Revises: None
Create Date: 2015-09-28 18:42:18.334750

"""

# revision identifiers, used by Alembic.
revision = '3dfd0f061d9f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
