"""empty message

Revision ID: 58af037a4d2d
Revises: None
Create Date: 2015-10-12 23:36:28.421662

"""

# revision identifiers, used by Alembic.
revision = '58af037a4d2d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_name', sa.String(length=64), nullable=True))
    op.drop_column('files', 'filename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('files', 'file_name')
    ### end Alembic commands ###
