"""empty message

Revision ID: 88934ee6dd4
Revises: 3dfd0f061d9f
Create Date: 2015-09-28 18:53:09.131361

"""

# revision identifiers, used by Alembic.
revision = '88934ee6dd4'
down_revision = '3dfd0f061d9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
